import { prisma } from '@/lib/db'
import { notFound } from 'next/navigation'
import TesteForm from './TesteForm'

export const TESTES: Record<string, {
  label: string
  color: string
  instrucoes: string
  perguntas: string[]
}> = {
  tdah: {
    label: 'TDAH — Déficit de Atenção e Hiperatividade',
    color: '#d97706',
    instrucoes: 'Para cada item, indique a frequência com que o comportamento ocorre:\n1 = Nunca · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre',
    perguntas: [
      'Dificuldade em manter atenção em tarefas ou atividades',
      'Comete erros por descuido em atividades escolares',
      'Parece não ouvir quando se fala diretamente com ele(a)',
      'Não segue instruções e não termina tarefas escolares',
      'Dificuldade em organizar tarefas e atividades',
      'Evita tarefas que exigem esforço mental prolongado',
      'Perde objetos necessários para tarefas (lápis, livros)',
      'Distrai-se facilmente por estímulos externos',
      'É agitado(a) ou mexe constantemente as mãos ou os pés',
      'Levanta da cadeira em situações em que deveria permanecer sentado(a)',
      'Corre ou trepa em situações inadequadas',
      'Dificuldade em brincar calmamente',
      'Fala em excesso',
      'Responde às perguntas antes que sejam concluídas',
      'Dificuldade em esperar a vez em jogos ou situações de grupo',
    ],
  },
  autismo: {
    label: 'TEA — Transtorno do Espectro Autista',
    color: '#7c3aed',
    instrucoes: 'Para cada item, indique a frequência ou intensidade observada:\n1 = Nunca / Ausente · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre / Muito intenso',
    perguntas: [
      'Faz contato visual durante interações sociais',
      'Responde quando chamado pelo seu nome',
      'Aponta com o dedo para mostrar interesse por algo',
      'Imita gestos, expressões ou ações dos outros',
      'Engaja-se em brincadeira simbólica (faz de conta)',
      'Demonstra interesse espontâneo por outras crianças',
      'Apresenta movimentos repetitivos (balançar, girar)',
      'Manifesta interesses muito restritos e intensos',
      'Apresenta reações incomuns a sons, texturas ou luz',
      'Usa objetos de forma não convencional (alinha, gira)',
      'Dificuldade em compreender expressões faciais',
      'Demonstra rigidez e dificuldade com mudanças de rotina',
      'Usa linguagem verbal de forma funcional e comunicativa',
      'Busca espontaneamente compartilhar experiências',
      'Apresenta comportamentos de autoestimulação ou autolesão',
    ],
  },
  dislexia: {
    label: 'Dislexia — Dificuldades de Leitura e Escrita',
    color: '#0284c7',
    instrucoes: 'Para cada item, indique a frequência com que a dificuldade é observada:\n1 = Nunca · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre',
    perguntas: [
      'Dificuldade em aprender e memorizar o alfabeto',
      'Confunde letras com formas semelhantes (b/d, p/q)',
      'Leitura em voz alta lenta, com erros ou omissões',
      'Dificuldade em dividir palavras em sílabas',
      'Erros ortográficos persistentes mesmo após instrução',
      'Dificuldade em identificar rimas',
      'Dificuldade em compreender o que acabou de ler',
      'Copia do quadro de forma lenta e com erros',
      'Confunde a sequência de letras nas palavras',
      'Dificuldade em seguir instruções escritas',
      'Problemas para memorizar sequências (dias, meses)',
      'Escrita em espelho ou inversões frequentes',
      'Dificuldade acentuada em aprender língua estrangeira',
      'Leitura silenciosa muito mais fácil que a oral',
      'Histórico familiar de dificuldades de leitura',
    ],
  },
  cars: {
    label: 'CARS — Escala de Avaliação do Autismo na Infância',
    color: '#be185d',
    instrucoes: 'Avalie cada área com base na observação comportamental:\n1 = Dentro do esperado para a idade · 2 = Levemente fora do esperado · 3 = Moderadamente fora do esperado · 4 = Muito fora do esperado · 5 = Extremamente fora do esperado',
    perguntas: [
      'Relação com pessoas — qualidade das interações sociais',
      'Imitação — capacidade de imitar sons, palavras ou ações',
      'Resposta emocional — adequação das respostas emocionais ao contexto',
      'Uso do corpo — controle, coordenação e movimentos do corpo',
      'Uso de objetos — forma como manipula e usa os objetos',
      'Adaptação a mudanças — reação a alterações na rotina',
      'Resposta visual — qualidade do uso funcional da visão',
      'Resposta auditiva — reação e atenção a estímulos sonoros',
      'Paladar, olfato e tato — respostas aos sentidos proximais',
      'Medo e ansiedade — presença e intensidade de medos',
      'Comunicação verbal — qualidade e funcionalidade da fala',
      'Comunicação não verbal — uso de gestos e expressões',
      'Nível de atividade — regularidade e intensidade da atividade motora',
      'Nível e consistência intelectual — variação no desempenho cognitivo',
      'Impressão geral — avaliação global do perfil comportamental',
    ],
  },
  snap4: {
    label: 'SNAP-IV — Escala de Avaliação de TDAH e TOD',
    color: '#d97706',
    instrucoes: 'Para cada comportamento, indique a intensidade:\n1 = Nunca / Raramente · 2 = Às vezes · 3 = Frequentemente · 4 = Muito frequentemente · 5 = Quase sempre',
    perguntas: [
      'Não presta atenção a detalhes ou comete erros por descuido',
      'Tem dificuldade de manter a atenção em tarefas ou brincadeiras',
      'Parece não ouvir quando se fala com ele diretamente',
      'Não segue instruções e não termina as tarefas',
      'Tem dificuldade para organizar tarefas e atividades',
      'Evita, não gosta ou reluta em realizar tarefas que exigem esforço mental prolongado',
      'Perde coisas necessárias para as atividades',
      'Distrai-se facilmente com estímulos externos',
      'É esquecido(a) nas atividades diárias',
      'Agita as mãos ou os pés, ou fica se mexendo na cadeira',
      'Levanta da cadeira na sala de aula ou em outras situações em que se espera que fique sentado(a)',
      'Corre em volta ou escala objetos em situações inapropriadas',
      'Tem dificuldade para brincar ou se envolver em atividades de lazer calmamente',
      'Está frequentemente "a mil" ou age como se estivesse "a todo vapor"',
      'Fala demais',
      'Dá respostas precipitadas antes que as perguntas sejam completadas',
      'Tem dificuldade de esperar a vez',
      'Interrompe ou se mete em conversa ou brincadeiras alheias',
    ],
  },
  eoca: {
    label: 'EOCA — Entrevista Operativa Centrada na Aprendizagem',
    color: '#0369a1',
    instrucoes: 'Avalie cada aspecto com base na observação durante as atividades propostas:\n1 = Não observado · 2 = Raramente · 3 = Em parte · 4 = Frequentemente · 5 = Sempre presente',
    perguntas: [
      'Demonstra interesse e motivação ao iniciar uma nova tarefa',
      'Mostra curiosidade frente ao material desconhecido',
      'Tolera a frustração diante de erros ou dificuldades',
      'Pede ajuda quando encontra dificuldades',
      'Segue sequências de instrução de duas ou mais etapas',
      'Usa linguagem para organizar e planejar a ação',
      'Estabelece relações entre o novo aprendizado e o já conhecido',
      'Demonstra flexibilidade para mudar estratégia quando necessário',
      'Mantém atenção sustentada durante a atividade',
      'Reconhece seus próprios erros e busca corrigi-los',
      'Tem consciência de suas capacidades e dificuldades',
      'Apresenta ritmo adequado para a faixa etária',
      'Demonstra prazer e satisfação ao aprender',
      'Relaciona-se de forma cooperativa em atividades em dupla',
      'Consegue transferir aprendizagens para situações novas',
    ],
  },
  motora_fina: {
    label: 'Avaliação de Coordenação Motora Fina',
    color: '#047857',
    instrucoes: 'Para cada habilidade, avalie a qualidade de execução observada:\n1 = Não consegue realizar · 2 = Realiza com muita dificuldade · 3 = Realiza com alguma dificuldade · 4 = Realiza com pequenas dificuldades · 5 = Realiza sem dificuldade',
    perguntas: [
      'Pega objetos pequenos entre polegar e indicador (pinça)',
      'Segura o lápis ou caneta de forma funcional',
      'Copia formas geométricas básicas (círculo, quadrado, triângulo)',
      'Traça linhas retas e curvas com controle adequado',
      'Recorta com tesoura seguindo um contorno',
      'Cola materiais com precisão',
      'Escreve letras com tamanho e espaçamento adequados',
      'Dobra papel seguindo instruções simples',
      'Enfia miçangas ou contas em um fio',
      'Desenha figura humana com proporções reconhecíveis',
      'Abre e fecha botões, zíperes e fechos',
      'Usa talheres adequadamente para a faixa etária',
      'Vira páginas de um livro uma por vez',
      'Constrói torre com blocos pequenos',
      'Copia padrões geométricos simples',
    ],
  },
  disgrafia: {
    label: 'Questionário de Rastreamento de Disgrafia',
    color: '#7c3aed',
    instrucoes: 'Para cada item, indique a frequência com que o comportamento é observado na escrita:\n1 = Nunca · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre',
    perguntas: [
      'A caligrafia é ilegível ou de difícil leitura',
      'As letras variam muito de tamanho dentro de uma mesma palavra',
      'A escrita sai do espaço das linhas repetidamente',
      'As letras são formadas de maneira inconsistente',
      'O espaçamento entre palavras é irregular',
      'Há mistura de letras maiúsculas e minúsculas sem regra',
      'Pressão excessiva ou insuficiente ao escrever',
      'O ritmo de escrita é muito lento para a faixa etária',
      'Apresenta cansaço ou dor na mão ao escrever',
      'Apaga excessivamente durante a escrita',
      'Troca a direção das letras (espelhamento)',
      'Tem dificuldade em manter a direção da escrita da esquerda para a direita',
      'Letras com hastes ou curvas mal formadas',
      'A linha de base da escrita é irregular (sobe e desce)',
      'Recusa ou evita atividades de escrita',
    ],
  },
  disortografia: {
    label: 'Questionário de Rastreamento de Disortografia',
    color: '#6d28d9',
    instrucoes: 'Para cada item, avalie a frequência com que o erro ortográfico ocorre:\n1 = Nunca · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre',
    perguntas: [
      'Troca letras com sons semelhantes (f/v, p/b, t/d)',
      'Omite letras ou sílabas em palavras',
      'Acrescenta letras desnecessárias nas palavras',
      'Inverte a ordem das letras ou sílabas',
      'Erros com uso de maiúsculas e minúsculas',
      'Dificuldade com acentuação gráfica',
      'Confusão com dígrafo e encontros consonantais',
      'Erros persistentes com palavras irregulares',
      'Troca letras visualmente similares (a/o, n/m)',
      'Segmentação inadequada das palavras (junto/separado)',
      'Dificuldade em usar pontuação corretamente',
      'Erros ortográficos mesmo após estudo e revisão',
      'Inconsistência: escreve a mesma palavra de formas diferentes',
      'Dificuldade em identificar e corrigir seus próprios erros',
      'A qualidade ortográfica cai quando escreve rápido',
    ],
  },
  lateralidade: {
    label: 'Avaliação de Lateralidade',
    color: '#0891b2',
    instrucoes: 'Para cada atividade, observe qual lado é usado predominantemente:\n1 = Sempre lado esquerdo · 2 = Preferencialmente esquerdo · 3 = Sem preferência definida (ambidestro) · 4 = Preferencialmente direito · 5 = Sempre lado direito',
    perguntas: [
      'Qual mão usa para escrever?',
      'Qual mão usa para desenhar?',
      'Qual mão usa para lançar uma bola?',
      'Qual mão usa para receber um objeto?',
      'Qual mão usa para escavar (pá, colher no chão)?',
      'Qual pé usa para chutar uma bola?',
      'Qual pé usa para dar o primeiro passo ao subir uma escada?',
      'Qual pé usa para ficar em equilíbrio (pular com um pé)?',
      'Qual olho usa para fechar um olho e mirar?',
      'Qual olho usa para olhar através de um tubo ou rolo de papel?',
      'Qual ouvido aproxima do telefone?',
      'Qual ouvido aproxima da porta para escutar barulho?',
      'Ao cruzar os braços, qual vai por cima?',
      'Ao entrelaçar os dedos, qual polegar fica por cima?',
      'Ao piscar um olho, qual olho pisca com mais facilidade?',
    ],
  },
  psicopedagogica: {
    label: 'Avaliação Psicopedagógica Escolar',
    color: '#374151',
    instrucoes: 'Avalie cada aspecto com base nas observações escolares e clínicas:\n1 = Muito abaixo do esperado · 2 = Abaixo do esperado · 3 = Na média esperada · 4 = Acima do esperado · 5 = Muito acima do esperado',
    perguntas: [
      'Desempenho em leitura oral (fluência, prosódia)',
      'Compreensão leitora (interpretação de textos)',
      'Produção escrita (organização, coerência)',
      'Ortografia (domínio das normas)',
      'Aritmética básica (operações fundamentais)',
      'Raciocínio lógico-matemático',
      'Resolução de problemas',
      'Atenção e concentração em sala',
      'Memória operacional / de trabalho',
      'Organização e planejamento das atividades',
      'Velocidade de processamento',
      'Relação com os pares (socialização)',
      'Relação com adultos (professores)',
      'Autoestima e autoconceito acadêmico',
      'Motivação e engajamento nas tarefas escolares',
    ],
  },
  tpac: {
    label: 'Triagem do TPAC — Transtorno do Processamento Auditivo Central',
    color: '#0f766e',
    instrucoes: 'Para cada item, indique a frequência com que a dificuldade é observada:\n1 = Nunca · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre',
    perguntas: [
      'Dificuldade em compreender fala em ambientes com ruído',
      'Pede repetição frequente mesmo com audição normal',
      'Confunde palavras com sons semelhantes ("bola/mola")',
      'Dificuldade em localizar a direção de sons',
      'Demora para responder a instruções verbais',
      'Distrai-se facilmente por sons do ambiente',
      'Dificuldade em seguir conversas com mais de uma pessoa',
      'Melhor desempenho quando recebe instruções por escrito',
      'Dificuldade com rimas e consciência fonológica',
      'Cansaço excessivo em situações de escuta prolongada',
      'Dificuldade em memorizar sequências auditivas (músicas, poesias)',
      'Confunde instruções similares ("senta/levanta", "entra/sai")',
      'Desempenho piora consideravelmente em ambientes reverberantes',
      'Dificuldade em aprender língua estrangeira pela via oral',
      'Histórico de otites de repetição na infância',
    ],
  },
  discalculia: {
    label: 'Avaliação de Discalculia (a partir de 8 anos)',
    color: '#b45309',
    instrucoes: 'Para cada item, indique a frequência com que a dificuldade é observada:\n1 = Nunca · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre',
    perguntas: [
      'Dificuldade em compreender o conceito de quantidade e número',
      'Confunde símbolos numéricos (3/8, 6/9)',
      'Erros em operações básicas (soma, subtração) sem razão aparente',
      'Dificuldade em memorizar tabuada mesmo após muito esforço',
      'Confunde ordem dos algarismos em números (13/31)',
      'Dificuldade em entender o valor posicional (unidade, dezena)',
      'Problemas para contar de trás para frente ou de 2 em 2',
      'Dificuldade com frações, decimais e porcentagens',
      'Demora excessiva para calcular mentalmente',
      'Usa os dedos para calcular mesmo após a faixa etária esperada',
      'Dificuldade em entender o conceito de tempo (horas, calendário)',
      'Problemas com estimativa e aproximação de valores',
      'Dificuldade em resolver problemas matemáticos contextualizados',
      'Ansiedade acentuada em situações que envolvem matemática',
      'Desempenho muito abaixo dos pares na disciplina de matemática',
    ],
  },
  altas_habilidades: {
    label: 'Avaliação de Altas Habilidades / Superdotação',
    color: '#dc2626',
    instrucoes: 'Para cada característica, indique a intensidade com que é observada:\n1 = Não observado · 2 = Raramente · 3 = Às vezes · 4 = Frequentemente · 5 = Sempre / Muito intenso',
    perguntas: [
      'Aprende rápido e com pouca repetição',
      'Vocabulário muito acima do esperado para a faixa etária',
      'Faz perguntas incomuns, profundas e instigantes',
      'Demonstra curiosidade intensa por temas específicos',
      'Apresenta raciocínio abstrato avançado',
      'Resolve problemas de forma criativa e pouco convencional',
      'Tem grande memória para informações de seu interesse',
      'Prefere companhia de crianças mais velhas ou adultos',
      'Apresenta alto senso de justiça e senso crítico',
      'Demonstra habilidade artística, musical ou corporal excepcional',
      'Lê vorazmente e em nível acima da faixa etária',
      'Demonstra alta concentração em atividades de seu interesse',
      'Produz ideias originais e inovadoras',
      'Apresenta hipersensibilidade emocional ou intensidade afetiva',
      'Demonstra liderança espontânea em grupos',
    ],
  },
}

export default async function AplicarTestePage({ params, searchParams }: { params: Promise<{ tipo: string }>; searchParams: Promise<Record<string, string>> }) {
  const { tipo } = await params
  const sp = await searchParams
  const config = TESTES[tipo]
  if (!config) notFound()

  const alunos = await prisma.aluno.findMany({ orderBy: { nome: 'asc' }, select: { id: true, nome: true } })
  const pacientes = await prisma.paciente.findMany({ orderBy: { nome: 'asc' }, select: { id: true, nome: true } })

  const preAlunoId = sp.alunoId || ''
  const prePacienteId = sp.pacienteId || ''

  return (
    <div style={{ maxWidth: 720 }}>
      <TesteForm tipo={tipo} config={config} alunos={alunos} pacientes={pacientes} preAlunoId={preAlunoId} prePacienteId={prePacienteId} />
    </div>
  )
}
